### ISSUE TITLE
put opentree on conda-forge

### ISSUE THREAD

**Issue by harmsm** [OpenTreeOfLife/python-opentree#23]
This library is extraordinarily useful. Would you be willing to make it installable by conda as well as pip? My lab is working on an ancestral sequence reconstruction [pipeline](https://topiary-asr.readthedocs.io/en/latest/installation.html#required-libraries) that relies on opentree, as well as some conda-only packages. It would be useful to be able to give users an option to install the whole pipeline with conda.

I would be happy to take point on submitting to conda-forge if helpful and okay with you. 

Thanks!

**Comment by harmsm** [comment]
I just submitted a PR with a draft meta.yaml file, if helpful.

**Comment by snacktavish** [comment]
Thanks! I merged it to development and updated it. 
https://github.com/OpenTreeOfLife/python-opentree/blob/development/meta.yaml

I have started walking through the steps at https://conda-forge.org/docs/maintainer/adding_pkgs.html

Was there a reason you used v0.0.3 for the meta.yml? I figured I would just submit it with v1.0.1, (honestly it reminds me that we should submit a newer release to pypi... but one thing at time) but if there is a reason to start with the 0.0.3 that is fine too.

**Comment by harmsm** [comment]
Oops, copied in wrong version number when making the template. No reason at all, in other words….

**Comment by snacktavish** [comment]
Ah - it's because we tagged it but never created a new release on GitHub! I just fixed that.

**Comment by harmsm** [comment]
👍

**Comment by snacktavish** [comment]
I am trying to locally test my recipe before submitting a PR to staged recipes (as described in https://conda-forge.org/docs/maintainer/adding_pkgs.html#staging-test-locally). 
I have forked the repo, and updated the recipe in /recipes in https://github.com/snacktavish/staged-recipes

However, when I try to run the tests using
`python build-locally.py `
from the top level dir, a bunch of stuff runs (I could share output), but at the end I get "There are no tempfile(s) to remove.
There are no logfile(s) to remove.
Found no recipes to build".

Any ideas?

**Comment by snacktavish** [comment]
gave up on local testing, submitted a PR and am letting the CI test it! https://github.com/conda-forge/staged-recipes/pull/20097

**Comment by harmsm** [comment]
🤞 Thanks for working on it!

**Comment by harmsm** [comment]
I noticed this is stalled out on conda-forge. When I requested the conda-forge repo I did not realize that *all* dependencies had to be on conda-forge, rather than just visible on conda via some channel. It seems like bioconda will be a more flexible option given dendropy is already on bioconda, not conda-forge. 

I created a recipe file for bioconda and have a [fork](https://github.com/harmsm/bioconda-recipes/tree/opentree) ready for a PR against bioconda master. If you like, I can do the PR. (I tried to test locally, but bioconda-utils seems to be very, very broken. It relies on an apparently abandoned GO program to interface with docker???) 

Thanks!

**Comment by snacktavish** [comment]
Ah nice! I will take a look this week. I was away last week and am digging out!

**Comment by harmsm** [comment]
Unfortunately, I’m my package is also my first conda-forge submission. I didn’t even get to that step before I hit the snag of having a few non-conda packages in my dependency tree. 

I’ve done a fair amount in conda, so maybe I would have ideas seeing output. Could you post output spew?

Thanks!

**Comment by snacktavish** [comment]
Hi Mike,
Sorry for dropping the ball on this! I suspect there is just an issue with my setup that it isn't even trying to build this recipe when I run build-locally.py, but here's all the output.

It doesn't seem like it is even trying any of the recipes :thinking: (the other ones happened to be in staged-recipes when I forked it)
```
$ ls recipes/
example  perl-file-chdir  perl-mime-base64  python-opentree
```

<details>
  <summary>Click to expand verbose output</summary>
  
 ```
$ python build-locally.py 
valid configs are {'win64', 'linux64_cuda102', 'linux64', 'osx64', 'linux64_cuda110', 'linux64_cuda111', 'linux64_cuda112'}
config not selected, please choose from the following:

1. linux64
2. linux64_cuda102
3. linux64_cuda110
4. linux64_cuda111
5. linux64_cuda112
6. osx64
7. win64

> 1
selected linux64
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 97
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-48-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.31GiB
 Name: byatt
 ID: YN25:ULNR:5DVO:HSYD:WVKW:FMBM:ZEZ2:YQZE:R6QW:BL5U:KHSD:BFEY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mctavishlab
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

.scripts/run_docker_build.sh: line 24: shyaml: command not found
WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils
Using default tag: latest
latest: Pulling from condaforge/linux-anvil-cos7-x86_64
2d473b07cdd5: Already exists 
dadc05df4b32: Pull complete 
Digest: sha256:1c1b355ecab912c157741dcd971f1db9d6d6fe9f0393f13e0b54828e6f85bb57
Status: Downloaded newer image for quay.io/condaforge/linux-anvil-cos7-x86_64:latest
quay.io/condaforge/linux-anvil-cos7-x86_64:latest
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
+ export PYTHONUNBUFFERED=1
+ PYTHONUNBUFFERED=1
+ cat
+ cp -r /home/conda/staged-recipes /home/conda/staged-recipes-copy
+ find /home/conda/staged-recipes-copy/recipes -maxdepth 1 -name .DS_Store -delete
+ echo 'Pending recipes.'
Pending recipes.
+ ls -la /home/conda/staged-recipes-copy/recipes
total 24
drwxr-xr-x  6 conda conda 4096 Oct 11 17:13 .
drwxr-xr-x 10 conda conda 4096 Oct 11 17:13 ..
drwxr-xr-x  2 conda conda 4096 Oct 11 17:13 example
drwxr-xr-x  2 conda conda 4096 Oct 11 17:13 perl-file-chdir
drwxr-xr-x  2 conda conda 4096 Oct 11 17:13 perl-mime-base64
drwxr-xr-x  2 conda conda 4096 Oct 11 17:13 python-opentree
+ echo 'Finding recipes merged in main and removing them from the build.'
Finding recipes merged in main and removing them from the build.
+ pushd /home/conda/staged-recipes/recipes
+ '[' False == True ']'
+ git ls-tree --name-only main -- .
+ xargs -I '{}' sh -c 'rm -rf ~/staged-recipes-copy/recipes/{} && echo Removing recipe: {}'
Removing recipe: example
Removing recipe: perl-file-chdir
Removing recipe: perl-mime-base64
Removing recipe: python-opentree
+ popd
+ conda index /home/conda/staged-recipes/build_artifacts
+ mamba install --yes --quiet 'conda>4.7.12' 'conda-forge-ci-setup=3.*' conda-forge-pinning networkx=2.4 'conda-build>=3.16' boa                                                                             
                                                                                                                                                                                                             
                  __    __    __    __                                                                                                                                                                       
                 /  \  /  \  /  \  /  \               
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

  Package                             Version  Build              Channel                   Size
──────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────────────────────

  + click                               8.1.3  py310hff52083_0    conda-forge/linux-64     152kB
  + conda-env                           2.6.0  1                  conda-forge/noarch         2kB
  + conda-forge-ci-setup               3.21.0  py310hce54274_100  conda-forge/linux-64      44kB
  + conda-forge-pinning   2022.10.11.03.04.53  hd8ed1ab_0         conda-forge/noarch        22kB
  + decorator                           5.1.1  pyhd8ed1ab_0       conda-forge/noarch        12kB
  + jq                                    1.6  h36c2ea0_1000      conda-forge/linux-64     354kB
  + networkx                              2.4  py_1               conda-forge/noarch         1MB
  + oniguruma                           6.9.8  h166bdaf_0         conda-forge/linux-64     440kB
  + shyaml                              0.6.2  pyhd3deb0d_0       conda-forge/noarch        22kB

  Summary:

  Install: 9 packages

  Total download: 2MB

──────────────────────────────────────────────────────────────────────────────────────────────────

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ export FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ export CI_SUPPORT=/home/conda/staged-recipes-copy/.ci_support
+ CI_SUPPORT=/home/conda/staged-recipes-copy/.ci_support
+ setup_conda_rc /home/conda/staged-recipes /home/conda/staged-recipes-copy/recipes /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
+ source run_conda_forge_build_setup
++ export PYTHONUNBUFFERED=1
++ PYTHONUNBUFFERED=1
++ conda config --env --set show_channel_urls true
++ conda config --env --set auto_update_conda false
++ conda config --env --set add_pip_as_python_dependency false
++ conda config --env --append aggressive_update_packages ca-certificates
++ conda config --env --remove-key aggressive_update_packages
++ conda config --env --append aggressive_update_packages ca-certificates
++ conda config --env --append aggressive_update_packages certifi
++ export CONDA_BLD_PATH=/home/conda/staged-recipes/build_artifacts
++ CONDA_BLD_PATH=/home/conda/staged-recipes/build_artifacts
++ set +u
++ [[ '' == \d\r\o\n\e ]]
++ [[ '' == \g\i\t\h\u\b\_\a\c\t\i\o\n\s ]]
++ export CPU_COUNT=2
++ CPU_COUNT=2
+++ cat /home/conda/staged-recipes/conda-forge.yml
+++ shyaml get-value channel_priority strict
++ conda config --env --set channel_priority strict
++ [[ ! -z '' ]]
++ '[' '!' -z linux64 ']'
++ '[' '!' -z '' ']'
++ cat /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
c_compiler:
- gcc
cxx_compiler:
- gxx
fortran_compiler:
- gfortran
target_platform:
- linux-64
channel_sources:
- conda-forge
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
cuda_compiler_version:
- None
++ set -u
++ mkdir -p /opt/conda/etc/conda/activate.d
++ echo 'export CONDA_BLD_PATH='\''/home/conda/staged-recipes/build_artifacts'\'''
++ '[' -n 2 ']'
++ echo 'export CPU_COUNT='\''2'\'''
++ echo 'export PYTHONUNBUFFERED='\''1'\'''
+++ cat /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
+++ shyaml get-value cuda_compiler_version.0 None
++ CUDA_VERSION=None
++ [[ None != \N\o\n\e ]]
++++ dirname /opt/conda/bin/run_conda_forge_build_setup
+++ cd /opt/conda/bin
+++ pwd
++ SCRIPT_DIR=/opt/conda/bin
++ source /opt/conda/bin/cross_compile_support.sh
++++ conda info --json
++++ jq -r .platform
+++ BUILD_PLATFORM=linux-64
+++ '[' -f /home/conda/staged-recipes-copy/.ci_support/linux64.yaml ']'
++++ cat /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
++++ shyaml get-value target_platform.0 linux-64
+++ HOST_PLATFORM=linux-64
+++ HOST_PLATFORM=linux-64
+++ [[ linux-64 != \l\i\n\u\x\-\6\4 ]]
++ '[' -f /home/conda/staged-recipes-copy/.ci_support/linux64.yaml ']'
+++ cat /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
+++ shyaml get-value MACOSX_DEPLOYMENT_TARGET.0 0
++ need_osx_sdk=0
++ [[ 0 != \0 ]]
++ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /opt/conda/.condarc
                          /home/conda/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.10.6.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/conda/staged-recipes/build_artifacts/pkg_cache
                          /opt/conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Linux/5.15.0-48-generic centos/7.9.2009 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

++ conda config --env --show-sources
==> /opt/conda/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
aggressive_update_packages:
  - ca-certificates
  - certifi
channel_priority: strict
channels:
  - conda-forge
show_channel_urls: True

==> /home/conda/.condarc <==
pkgs_dirs:
  - /home/conda/staged-recipes/build_artifacts/pkg_cache
  - /opt/conda/pkgs
channels:
  - conda-forge
show_channel_urls: True
conda-build:
  root-dir: /home/conda/staged-recipes/build_artifacts

==> envvars <==
bld_path: /home/conda/staged-recipes/build_artifacts

++ conda list --show-channel-urls
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
boa                       0.12.0             pyha770c72_4    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
chardet                   5.0.0           py310hff52083_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
conda                     22.9.0          py310hff52083_1    conda-forge
conda-build               3.22.0          py310hff52083_2    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-forge-ci-setup      3.21.0          py310hce54274_100    conda-forge
conda-forge-pinning       2022.10.11.03.04.53      hd8ed1ab_0    conda-forge
conda-package-handling    1.9.0           py310h5764c6d_0    conda-forge
cryptography              38.0.1          py310h597c629_0    conda-forge
curl                      7.85.0               h7bff187_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
future                    0.18.2          py310hff52083_5    conda-forge
gettext                   0.19.8.1          h27087fc_1009    conda-forge
git                       2.38.0          pl5321h5fbbf19_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310hff52083_0    conda-forge
importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jq                        1.6               h36c2ea0_1000    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310hff52083_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libcurl                   7.85.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblief                   0.12.2               h27087fc_0    conda-forge
libmamba                  0.27.0               h0dd8ff0_0    conda-forge
libmambapy                0.27.0          py310hab0e683_0    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.22               h6239696_0    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.12               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.27.0          py310hf87f941_0    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
nbformat                  5.6.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.4                        py_1    conda-forge
oniguruma                 6.9.8                h166bdaf_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.15.0               h58526e2_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
prompt_toolkit            3.0.31               hd8ed1ab_0    conda-forge
psutil                    5.9.2           py310h5764c6d_0    conda-forge
py-lief                   0.12.2          py310hd8f1fbe_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py310h5764c6d_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0             py310hff52083_1    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.4             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rich                      12.6.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel.yaml               0.17.21         py310h5764c6d_1    conda-forge
ruamel.yaml.clib          0.2.6           py310h5764c6d_1    conda-forge
ruamel_yaml               0.15.80         py310h5764c6d_1007    conda-forge
setuptools                65.4.1             pyhd8ed1ab_0    conda-forge
shyaml                    0.6.2              pyhd3deb0d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
su-exec                   0.2               h166bdaf_1003    conda-forge
tini                      0.19.0               h166bdaf_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
watchgod                  0.8.2              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
+ find /home/conda/staged-recipes-copy/recipes -mindepth 2 -maxdepth 2 -type f -name yum_requirements.txt
+ xargs -n1 cat
+ grep -v -e '^#' -e '^$'
+ xargs -r /usr/bin/sudo -n yum install -y
+ test 1 == 1
+ python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Updating build index: /home/conda/staged-recipes/build_artifacts

Will remove 9 (2.2 MB) tarball(s).
Will remove 1 index cache(s).
Will remove 26 (495.5 MB) package(s).
There are no tempfile(s) to remove.
There are no logfile(s) to remove.
Found no recipes to build
+ touch /home/conda/staged-recipes/build_artifacts/conda-forge-build-done

```
</details>

**Comment by snacktavish** [comment]
Aha! Progress. Verbose below, but the key part is:

>  Unsatisfiable dependencies for platform linux-64: {'nosetests', 'm2r', "dendropy[version='>=4.4.0']
m2r is just for the docs, and nose is for testing which presumably doesn't have to happen on conda, but dendropy is pivotal.

Nose and dendropy can be installed using:
conda install -c bioconda dendropy
conda install -c conda-forge nose 

But on a quick google I don't see how to add channels to the meta.yml

<details>
  <summary>Click to expand verbose output</summary>

```
conda build python-opentree/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for python-opentree
INFO:conda_build.metadata:Attempting to finalize metadata for python-opentree
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['python-opentree-1.0.1-py_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/ejmctavish/.conda/envs/testenv/conda-bld/python-opentree_1665510019295/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                
    _openmp_mutex:    5.1-1_gnu               
    ca-certificates:  2022.07.19-h06a4308_0   
    certifi:          2022.9.24-py37h06a4308_0
    ld_impl_linux-64: 2.38-h1181459_1         
    libffi:           3.3-he6710b0_2          
    libgcc-ng:        11.2.0-h1234567_1       
    libgomp:          11.2.0-h1234567_1       
    libstdcxx-ng:     11.2.0-h1234567_1       
    ncurses:          6.3-h5eee18b_3          
    openssl:          1.1.1q-h7f8727e_0       
    pip:              22.2.2-py37h06a4308_0   
    python:           3.7.13-h12debd9_0       
    readline:         8.1.2-h7f8727e_1        
    setuptools:       63.4.1-py37h06a4308_0   
    sqlite:           3.39.3-h5082296_0       
    tk:               8.6.12-h1ccaba5_0       
    wheel:            0.37.1-pyhd3eb1b0_0     
    xz:               5.2.6-h5eee18b_0        
    zlib:             1.2.12-h5eee18b_3       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/ejmctavish/.conda/envs/testenv/conda-bld/work 
  Test:
 /home/ejmctavish/.conda/envs/testenv/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/ejmctavish/.conda/envs/testenv/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/ejmctavish/.conda/envs/testenv/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/environ.py", line 799, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/plan.py", line 476, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
    should_retry_solve)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/core/solve.py", line 317, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/core/solve.py", line 607, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/resolve.py", line 556, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/resolve.py", line 577, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda/resolve.py", line 289, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - nosetests
  - m2r
  - dendropy[version='>=4.4.0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ejmctavish/.conda/envs/testenv/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 496, in main
    execute(sys.argv[1:])
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 487, in execute
    verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/build.py", line 3096, in build_tree
    notest=notest,
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/build.py", line 2131, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/build.py", line 2009, in create_build_envs
    raise e
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/build.py", line 1999, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/home/ejmctavish/.conda/envs/testenv/lib/python3.7/site-packages/conda_build/environ.py", line 801, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'nosetests', 'm2r', "dendropy[version='>=4.4.0']"}
```
</details>

**Comment by harmsm** [comment]
Thanks for working on this! (This stuff is no fun, so I really appreciate it). 

One question: are you trying to get this up on conda-forge or on bioconda? I originally suggested conda-forge, but that *only* allows dependencies on conda-forge, which is basically impossible on my end as well. 

Bioconda lists the following for their dependencies (https://bioconda.github.io/contributor/guidelines.html#bioconda-recipe-checklist)

<paste>
There is currently no mechanism to define, in the meta.yaml file, that a particular dependency should come from a particular channel. This means that a recipe must have its dependencies in one of the following:
as-yet-unbuilt recipes in the repo but that will be included in the PR
conda-forge channel
bioconda channel
default Anaconda channel
</paste>


Mike
